title: K0SWE Blog
email: k0swe@arrl.net
description: >-
  Events and projects for amateur radio operator K0SWE, a.k.a. Chris.
baseurl: ""
url: "https://k0swe.radio"
github_username: xylo04
paginate: 8

# Build settings
theme: minima

plugins:
  - jekyll-paginate

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
exclude:
  - .idea/
  - .jekyll-cache/
  - .sass-cache/
  - deploy.sh
  - Gemfile
  - Gemfile.lock
  - gemfiles/
  - node_modules/
  - resize-images.sh
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
